CREATE TABLE IF NOT EXISTS task_results (
    task_id VARCHAR PRIMARY KEY,
    user_id VARCHAR,
    trace_back TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result BYTEA,
);
